<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ool_lead"
 *
 * Auto generated by Extension Builder 2019-03-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'lead',
    'description' => 'Leads management BETA testing',
    'category' => 'plugin',
    'author' => 'Fahri Tardif',
    'author_email' => 'f.tardif.b@gmail.com',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
